import { combineReducers } from "redux";
import { posts, postsHasErrored, postsIsLoading } from "./posts";
import {
  post,
  postHasErrored,
  postIsLoading,
  postErrorMessge,
  newPostSuccess,
} from "./post";
import {
  user,
  loginHasErrored,
  loginIsLoading,
  loginErrorMessage,
  authenticated,
  metaMask,
} from "./login";
import {
  registrationSuccess,
  registrationIsLoading,
  registrationErrorMessage,
  registrationHasErrored,
} from "./register";
import {
  contract,
  contractFetchHasErrored,
  contractFetchIsLoading,
  collectionDetail,
  collectionDetailFetchHasErrored,
  collectionDetailFetchIsLoading,
  collectionStatus,
  collectionStatusFetchHasErrored,
  collectionStatusFetchIsLoading,
  collectionBackend,
  collectionBackendFetchHasErrored,
  collectionBackendFetchIsLoading,
  collectionEvent,
  collectionEventFetchHasErrored,
  collectionEventFetchIsLoading,
  collectionAsset,
  collectionAssetFetchHasErrored,
  collectionAssetFetchIsLoading,
  collectionSearch,
  collectionSearchHasErrored,
  collectionSearchIsLoading,
  collectionStats,
  collectionStatsFetchHasErrored,
  collectionStatsFetchIsLoading,
  collectionOrder,
  collectionOrderFetchHasErrored,
  collectionOrderFetchIsLoading,
} from "./collections";
export default combineReducers({
  posts,
  postsHasErrored,
  postsIsLoading,
  post,
  postHasErrored,
  postIsLoading,
  postErrorMessge,
  newPostSuccess,
  user,
  loginHasErrored,
  loginIsLoading,
  loginErrorMessage,
  authenticated,
  registrationSuccess,
  registrationIsLoading,
  registrationErrorMessage,
  registrationHasErrored,
  metaMask,
  contract,
  contractFetchHasErrored,
  contractFetchIsLoading,
  collectionDetail,
  collectionDetailFetchHasErrored,
  collectionDetailFetchIsLoading,
  collectionStatus,
  collectionStatusFetchHasErrored,
  collectionStatusFetchIsLoading,
  collectionBackend,
  collectionBackendFetchIsLoading,
  collectionBackendFetchHasErrored,
  collectionEvent,
  collectionEventFetchHasErrored,
  collectionEventFetchIsLoading,
  collectionAsset,
  collectionAssetFetchHasErrored,
  collectionAssetFetchIsLoading,
  collectionSearch,
  collectionSearchHasErrored,
  collectionSearchIsLoading,
  collectionStats,
  collectionStatsFetchHasErrored,
  collectionStatsFetchIsLoading,
  collectionOrder,
  collectionOrderFetchIsLoading,
  collectionOrderFetchHasErrored,
});
